name: BuildOpenAL

permissions:
  contents: read
  packages: write

on: workflow_dispatch

jobs:
  build_native:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rid: linux-x64
            prereqs: |
              sudo apt install ca-certificates curl gpg
              curl -fsSL https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo gpg --dearmor --yes -o /usr/share/keyrings/kitware-archive-keyring.gpg
              cat <<EOF | sudo tee /etc/apt/sources.list.d/kitware.sources
              Types: deb
              URIs: https://apt.kitware.com/ubuntu
              Suites: $(lsb_release -cs)
              Components: main
              Architectures: $(dpkg --print-architecture)
              Signed-By: /usr/share/keyrings/kitware-archive-keyring.gpg
              EOF
              sudo apt update
              sudo apt-get install -y cmake gcc-12 g++-12 libpulse-dev libasound2-dev libpipewire-0.3-dev
            cmakeargs: -B build -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12 -DALSOFT_EXAMPLES:BOOL="0" -DALSOFT_BACKEND_OBOE:BOOL="0" -DALSOFT_BACKEND_WASAPI:BOOL="0" -DALSOFT_INSTALL_UTILS:BOOL="0" -DALSOFT_BACKEND_WAVE:BOOL="0" -DALSOFT_INSTALL_EXAMPLES:BOOL="0" -DALSOFT_UTILS:BOOL="0" -DALSOFT_BACKEND_PORTAUDIO:BOOL="0" -DALSOFT_BACKEND_OPENSL:BOOL="0" -DALSOFT_BACKEND_SDL2:BOOL="1" -DALSOFT_BACKEND_WINMM:BOOL="0" -DALSOFT_BACKEND_COREAUDIO:BOOL="0" -DALSOFT_BACKEND_DSOUND:BOOL="0" -DALSOFT_INSTALL_HRTF_DATA:BOOL="0" -DALSOFT_BACKEND_SDL3:BOOL="1" -DALSOFT_INSTALL:BOOL="0" -DALSOFT_INSTALL_CONFIG:BOOL="0" -DALSOFT_INSTALL_AMBDEC_PRESETS:BOOL="0" 
            linkerfiles: openal-soft/build/libopenal.a
            libfiles: openal-soft/build/libopenal.so
          - os: windows-2026
            rid: win-x64
            prereqs: echo "Hi there."
            cmakeargs: -B build -A x64 -DALSOFT_BACKEND_JACK:BOOL="0" -DALSOFT_INSTALL_CONFIG:BOOL="0" -DALSOFT_ENABLE_MODULES:BOOL="1" -DALSOFT_BACKEND_COREAUDIO:BOOL="0" -DALSOFT_BACKEND_PIPEWIRE:BOOL="0" -DALSOFT_BACKEND_WINMM:BOOL="0" -DALSOFT_BACKEND_DSOUND:BOOL="1" -DALSOFT_BACKEND_OPENSL:BOOL="0" -DALSOFT_BACKEND_PORTAUDIO:BOOL="0" -DALSOFT_UTILS:BOOL="0" -DALSOFT_INSTALL_EXAMPLES:BOOL="0" -DALSOFT_INSTALL_UTILS:BOOL="0" -DALSOFT_BACKEND_PULSEAUDIO:BOOL="0" -DALSOFT_BACKEND_WAVE:BOOL="0" -DALSOFT_EXAMPLES:BOOL="0" -DALSOFT_BACKEND_OBOE:BOOL="0" -DALSOFT_BACKEND_WASAPI:BOOL="1" 
            linkerfiles: openal-soft/build/Release/OpenAL32.lib
            libfiles: openal-soft/build/Release/OpenAL32.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Clone Submodules
        run: git submodule update --init
      - name: Install Tools
        run: ${{ matrix.prereqs }}
      - name: Print CMake version
        run: cmake --version
      - name: CMake Configure Shared
        run: cmake ${{ matrix.cmakeargs }}
        working-directory: openal-soft
      - name: CMake Build Shared
        run: cmake --build . --config Release -j
        working-directory: openal-soft/build
      - name: CMake Configure Static
        run: cmake ${{ matrix.cmakeargs }} -DLIBTYPE=STATIC
        working-directory: openal-soft
      - name: CMake Build Static
        run: cmake --build . --config Release -j
        working-directory: openal-soft/build
      - name: Make Output Folder
        run: |
         mkdir -p build_native/${{ matrix.rid }}
         cp ${{ matrix.linkerfiles }} build_native/${{ matrix.rid }}
         cp ${{ matrix.libfiles }} build_native/${{ matrix.rid }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.rid }}
          path: build_native