name: BuildGLFW

permissions:
  contents: read
  packages: write

on: workflow_dispatch

jobs:
  build_native:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rid: linux-x64
            prereqs: |
              sudo apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
              echo "GLFWAPI void* glfwGetWin32Window(GLFWwindow* window);" >> glfw/src/glfw3native.h
              cat >> glfw/src/window.c<< EOF
              GLFWAPI void* glfwGetWin32Window(GLFWwindow* handle)
              {
                  return NULL;
              }
              EOF
            cmakeargsdynamic: -B build -DBUILD_SHARED_LIBS=ON
            cmakeargsstatic: -B build -DBUILD_SHARED_LIBS=OFF -DLIBTYPE=STATIC -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE
            cmakeargscommon: -DGLFW_BUILD_DOCS:BOOL="0" -DGLFW_BUILD_TESTS:BOOL="0" -DGLFW_BUILD_EXAMPLES:BOOL="0" 
            linkerfiles: glfw/build/src/libglfw3.a
            libfiles: glfw/build/src/libglfw.so
          - os: windows-2022
            rid: win-x64
            prereqs: echo "Hi there."
            cmakeargsdynamic: -B build -A x64 -DBUILD_SHARED_LIBS=ON
            cmakeargsstatic: -B build -A x64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DBUILD_SHARED_LIBS=OFF -DLIBTYPE=STATIC -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE
            cmakeargscommon: -DGLFW_BUILD_DOCS:BOOL="0" -DGLFW_BUILD_TESTS:BOOL="0" -DGLFW_BUILD_EXAMPLES:BOOL="0" 
            linkerfiles: glfw/build/src/Release/glfw3.lib
            libfiles: glfw/build/src/Release/glfw3.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Clone Submodules
        run: git submodule update --init
      - name: Install Tools
        run: ${{ matrix.prereqs }}
      - name: CMake Configure Shared
        run: cmake ${{ matrix.cmakeargsdynamic }} ${{ matrix.cmakeargscommon }}
        working-directory: glfw
      - name: CMake Build Shared
        run: cmake --build . --config Release -j
        working-directory: glfw/build
      - name: CMake Configure Static
        run: cmake ${{ matrix.cmakeargsstatic }} ${{ matrix.cmakeargscommon }}
        working-directory: glfw
      - name: CMake Build Static
        run: cmake --build . --config Release -j
        working-directory: glfw/build
      - name: Make Output Folder
        run: |
         mkdir -p build_native/${{ matrix.rid }}
         cp ${{ matrix.linkerfiles }} build_native/${{ matrix.rid }}
         cp ${{ matrix.libfiles }} build_native/${{ matrix.rid }}
      - name: Strip Symbols (linux)
        if: runner.os == 'Linux'
        run: strip build_native/linux-x64/*.so
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.rid }}
          path: build_native
  pack:
    runs-on: ubuntu-22.04
    needs: build_native
    steps:
      - uses: actions/checkout@v4
      - name: Get Native Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: native-*
          path: glfw-native
          merge-multiple: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: pack
        run: dotnet pack -c Release
        working-directory: csharp/Helion.GLFW
      - name: Make Output Folder
        run: |
          mkdir -p build_managed
          cp csharp/Helion.GLFW/bin/Release/*.nupkg build_managed
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Helion.GLFW
          path: build_managed
