name: BuildGLFW

permissions:
  contents: read
  packages: write

on: workflow_dispatch

jobs:
  build_native:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rid: linux-x64
            prereqs: |
              sudo apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
              echo "GLFWAPI void* glfwGetWin32Window(GLFWwindow* window);" >> src/glfw3native.h
              cat >> src/window.c<< EOF
              GLFWAPI void* glfwGetWin32Window(GLFWwindow* handle)
              {
                  return NULL;
              }
              EOF
            cmakeargs: -B build
            linkerfiles: glfw/build/src/libglfw3.a
            libfiles: glfw/build/src/libglfw.so
          - os: windows-2022
            rid: win-x64
            prereqs: echo "Hi there."
            cmakeargs: -B build -A x64
            linkerfiles: glfw/build/src/Release/glfw3.lib
            libfiles: glfw/build/src/Release/glfw3.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Clone Submodules
        run: git submodule update --init
      - name: Install Tools
        run: ${{ matrix.prereqs }}
      - name: CMake Configure Static
        run: cmake ${{ matrix.cmakeargs }} -DGLFW_BUILD_DOCS:BOOL="0" -DBUILD_SHARED_LIBS:BOOL="0" -DGLFW_BUILD_TESTS:BOOL="0" -DGLFW_BUILD_EXAMPLES:BOOL="0" 
        working-directory: glfw
      - name: CMake Build Static
        run: cmake --build . --config Release -j
        working-directory: glfw/build
      - name: CMake Configure Shared
        run: cmake ${{ matrix.cmakeargs }} -DGLFW_BUILD_DOCS:BOOL="0" -DBUILD_SHARED_LIBS:BOOL="1" -DGLFW_BUILD_TESTS:BOOL="0" -DGLFW_BUILD_EXAMPLES:BOOL="0" 
        working-directory: glfw
      - name: CMake Build Shared
        run: cmake --build . --config Release -j
        working-directory: glfw/build
      - name: Make Output Folder
        run: |
         mkdir -p build_native/${{ matrix.rid }}
         cp ${{ matrix.linkerfiles }} build_native/${{ matrix.rid }}
         cp ${{ matrix.libfiles }} build_native/${{ matrix.rid }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.rid }}
          path: build_native